AllCops:
  NewCops: enable

plugins:
  - rubocop-rails
  - rubocop-performance

require:
  - rubocop-capybara

Metrics/BlockLength:
  Exclude:
    - "config/environments/development.rb"
  Max: 30

Gemspec/AddRuntimeDependency:
  Enabled: true
Gemspec/DeprecatedAttributeAssignment:
  Enabled: true
Rails/ActionControllerFlashBeforeRender:
  Enabled: true


# ドキュメントコメントが無くてもエラーが出ないようにする
Style/Documentation:
  Enabled: false
