AllCops:
  NewCops: enable

plugins:
  - rubocop-rails
  - rubocop-performance

require:
  - rubocop-capybara

Metrics/BlockLength:
  Exclude:
    - "config/environments/development.rb"
  Max: 30

Gemspec/AddRuntimeDependency:
  Enabled: true
Gemspec/DeprecatedAttributeAssignment:
  Enabled: true
Rails/ActionControllerFlashBeforeRender:
  Enabled: true


# ドキュメントコメントが無くてもエラーが出ないようにする
Style/Documentation:
  Enabled: false

# 特定ファイルだけ長さ警告を無視
Layout/LineLength:
  Exclude:
    - "config/initializers/devise.rb"

# 長さ警告の上限を変更
Metrics/MethodLength:
  Max: 15  

Metrics/AbcSize:
  Max: 30
