FROM ruby:3.3.6

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# Node.jsと公式Yarnリポジトリを使ってインストールする
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
  && apt-get update -qq \
  && apt-get install -y \
    nodejs \
    yarn \
    build-essential \
    libpq-dev \
    vim \
    imagemagick \
    libvips \
  && rm -rf /var/lib/apt/lists/*


# 作業ディレクトリ作成
RUN mkdir /myapp
WORKDIR /myapp

# bundlerを最新にしておく（webpackerのgemインストールに必要なため）
RUN gem install bundler

# ソースコードコピー
COPY . /myapp
